apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-app-deployment
  labels:
    app: minikube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-app
  template:
    metadata:
      labels:
        app: minikube-app
    spec:
      nodeName: minikube
      containers:
        - name: minikube-app-server
          image: inceonur/minikube-app:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              #  memory: 1Gi
              cpu: 10m
            requests:
              #  memory: 400Mi
              cpu: 5m

---
apiVersion: v1
kind: Service
metadata:
  name: minikube-app-service
spec:
  selector:
    app: minikube-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110
