apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-app-deployment
  labels:
    app: minikube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-app
  template:
    metadata:
      labels:
        app: minikube-app
    spec:
      containers:
        - name: minikube-app-server
          image: inceonur/minikube-app:latest
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: minikube-app-service
spec:
  selector:
    app: minikube-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31110
