kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: minikube-app-deployment

spec:
  scaleTargetRef:
    kind: Deployment
    name: minikube-app-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          name: main-route
          target:
            type: Value
            value: 10k