kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: minikube-app-deployment

spec:
  scaleTargetRef:
    kind: Deployment
    name: minikube-app-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    #  - type: Resource
    #   resource:
    #    name: memory
    #    target:
    #      type: AverageValue
  #    averageValue: 300Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
